/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-10-26 18:41:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/home/../common/header.jsp", Long.valueOf(1603737679287L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("        #mainTop {\r\n");
      out.write("            width: 1260px;\r\n");
      out.write("            margin: 10px auto 12px;\r\n");
      out.write("        }     \r\n");
      out.write("        #mainTop>.mainTop1 {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            float: left;\r\n");
      out.write("            \r\n");
      out.write("            width: 942px;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        #mainTop>.mainTop2 {\r\n");
      out.write("            float: right;\r\n");
      out.write("            width: 306px;\r\n");
      out.write("        }\r\n");
      out.write("        #mainTop>.mainTop3 {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 942px;\r\n");
      out.write("        }\r\n");
      out.write("\t.login-main {\r\n");
      out.write("            width: 304px;\r\n");
      out.write("            height: 165px;\r\n");
      out.write("            margin: 0 0 12px;\r\n");
      out.write("            border: 1px solid #e5e5e5;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .login-main__action>a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 264px;\r\n");
      out.write("            height: 44px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            border: 1px solid #d1d1d1;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            line-height: 44px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .login-main__guide {\r\n");
      out.write("            height: 54px;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            line-height: 54px;\r\n");
      out.write("            letter-spacing: -1px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #666;\r\n");
      out.write("        }\r\n");
      out.write("        .login-main__member {\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border-top: 1px solid #e5e5e5;\r\n");
      out.write("            line-height: 40px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background-color: #f0f0f0;\r\n");
      out.write("        }\r\n");
      out.write("        .login-main__member>li {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-left: 4px;\r\n");
      out.write("            padding-left: 9px;\r\n");
      out.write("            background: url(//image.alba.kr/e/common/202009/header.png) no-repeat -149px 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .login-main__action {\r\n");
      out.write("            margin-bottom: 24px;\r\n");
      out.write("        }\r\n");
      out.write("        .choice_box{\r\n");
      out.write("        \twidth : 250px;\r\n");
      out.write("        \tborder : 1px solid #9e9e9e;\r\n");
      out.write("        \theight : 200px;\r\n");
      out.write("        \tfloat : left;\r\n");
      out.write("        \tpadding-top : 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .mini_title{\r\n");
      out.write("        \tbackground-color : #9e9e9e;\r\n");
      out.write("        \t width : 100%;\r\n");
      out.write("        \t  height : 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .mini_content{\r\n");
      out.write("        \theight : 250px;\r\n");
      out.write("        \tborder : 1px solid #9e9e9e;\r\n");
      out.write("        \tmargin-top : 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .ad_banner{\r\n");
      out.write("        \theight : 590px;\r\n");
      out.write("        \tborder : 1px solid;\r\n");
      out.write("        }\r\n");
      out.write("        .choice_title{\r\n");
      out.write("        \ttext-align : center;\r\n");
      out.write("        \tfont-size : 20px;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" crossorigin=\"anonymous\">\r\n");
      out.write("    <<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 초기화 */\r\n");
      out.write("        html {overflow-y:scroll}\r\n");
      out.write("        body {margin:0;padding:0;font-size:0.75em;font-family:'Malgun Gothic', dotum, sans-serif;background:#fff}\r\n");
      out.write("        html, h1, h2, h3, h4, h5, h6, form, fieldset, img {margin:0;padding:0;border:0}\r\n");
      out.write("        h1, h2, h3, h4, h5, h6 {font-size:1em;font-family:'Malgun Gothic', sans-serif}\r\n");
      out.write("        article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {display:block}\r\n");
      out.write("\r\n");
      out.write("        ul, dl,dt,dd {margin:0;padding:0;list-style:none}\r\n");
      out.write("        legend {position:absolute;margin:0;padding:0;font-size:0;line-height:0;text-indent:-9999em;overflow:hidden}\r\n");
      out.write("        label, input, button, select, img {vertical-align:middle;font-size:1em}\r\n");
      out.write("        input, button {margin:0;padding:0;font-family:'Malgun Gothic', sans-serif;font-size:1em}\r\n");
      out.write("        input[type=\"submit\"] {cursor:pointer}\r\n");
      out.write("        button {cursor:pointer}\r\n");
      out.write("\r\n");
      out.write("        p {margin:0;padding:0;word-break:break-all}\r\n");
      out.write("        hr {display:none}\r\n");
      out.write("        pre {overflow-x:scroll;font-size:1.1em}\r\n");
      out.write("        a {color:#000;text-decoration:none}\r\n");
      out.write("\r\n");
      out.write("        .placeholdersjs {color:#aaa !important}\r\n");
      out.write("\r\n");
      out.write("        /* 레이아웃 크기 지정 */\r\n");
      out.write("        #hd, #wrapper, #ft {min-width:1200px}\r\n");
      out.write("\r\n");
      out.write("        #hd_pop,\r\n");
      out.write("        #hd_wrapper,\r\n");
      out.write("        #tnb .inner,\r\n");
      out.write("\r\n");
      out.write("        #gnb .gnb_wrap,\r\n");
      out.write("        #container_wr,\r\n");
      out.write("        #ft_wr {width:1200px}\r\n");
      out.write("\r\n");
      out.write("        /* 상단 레이아웃 */\r\n");
      out.write("        #hd {background:#ffffff; }\r\n");
      out.write("        #hd_h1 {\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            font-size:0;\r\n");
      out.write("            line-height:0;\r\n");
      out.write("            overflow:hidden\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #tnb {margin:0 auto}\r\n");
      out.write("        #tnb:after {display:block;\r\n");
      out.write("            clear:both;\r\n");
      out.write("            content:\"\"\r\n");
      out.write("        }\r\n");
      out.write("        #tnb .inner {margin:0 auto}\r\n");
      out.write("\r\n");
      out.write("        #hd_wrapper {position:relative;\r\n");
      out.write("            margin:0 auto 20px auto;\r\n");
      out.write("            zoom:1\r\n");
      out.write("        }\r\n");
      out.write("        #hd_wrapper:after {\r\n");
      out.write("            display:block;\r\n");
      out.write("            visibility:hidden;\r\n");
      out.write("            clear:both;\r\n");
      out.write("            content:\"\"\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #logo {\r\n");
      out.write("            float:left;\r\n");
      out.write("            padding:20px 0 0;\r\n");
      out.write("             margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hd_sch_wr {\r\n");
      out.write("            float:left;\r\n");
      out.write("            padding:30px 0;\r\n");
      out.write("            width:445px;\r\n");
      out.write("            margin-left:12%\r\n");
      out.write("        }\r\n");
      out.write("        #hd_sch h3 {\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            font-size:0;\r\n");
      out.write("            line-height:0;\r\n");
      out.write("            overflow:hidden\r\n");
      out.write("        }\r\n");
      out.write("        #hd_sch {\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            overflow:hidden\r\n");
      out.write("        }\r\n");
      out.write("        #hd_sch #sch_stx {\r\n");
      out.write("            float:left;\r\n");
      out.write("            width:385px;\r\n");
      out.write("            height:45px;\r\n");
      out.write("            padding-left:10px;\r\n");
      out.write("            border-radius:30px 0 0 30px;\r\n");
      out.write("            border:2px solid #ffd203;\r\n");
      out.write("            border-right:0;\r\n");
      out.write("            font-size:1.25em;\r\n");
      out.write("        }\r\n");
      out.write("        #hd_sch #sch_submit {\r\n");
      out.write("            float:left;\r\n");
      out.write("            width:60px;\r\n");
      out.write("            height:45px;\r\n");
      out.write("            border:3;\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            color:#000000;\r\n");
      out.write("            border-radius:0 30px 30px 0;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            font-size:16px;\r\n");
      out.write("            border:2px solid #ffd203;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #hd_qnb {\r\n");
      out.write("            float:right;\r\n");
      out.write("            text-align:right\r\n");
      out.write("        }\r\n");
      out.write("        #hd_qnb:after {\r\n");
      out.write("            display:block;\r\n");
      out.write("            visibility:hidden;\r\n");
      out.write("            clear:both;\r\n");
      out.write("            content:\"\"\r\n");
      out.write("        }\r\n");
      out.write("        #hd_qnb li {\r\n");
      out.write("            float:left;\r\n");
      out.write("            font-size:1.083em;\r\n");
      out.write("            line-height:14px;\r\n");
      out.write("            border-right:1px solid #4a4a4a;\r\n");
      out.write("            position:relative;\r\n");
      out.write("            text-align:center;\r\n");
      out.write("            margin:15px 10px 15px 0;\r\n");
      out.write("            padding-right:10px\r\n");
      out.write("        }\r\n");
      out.write("        #hd_qnb li:last-child {\r\n");
      out.write("            padding-right:0;\r\n");
      out.write("            margin-right:0;\r\n");
      out.write("            border-right:0\r\n");
      out.write("        }\r\n");
      out.write("        #hd_qnb li span {\r\n");
      out.write("            display:block;\r\n");
      out.write("            margin-top:5px;\r\n");
      out.write("            font-size:0.8em\r\n");
      out.write("        }\r\n");
      out.write("        #hd_qnb li a {\r\n");
      out.write("            display:inline-block;\r\n");
      out.write("            color:#000000\r\n");
      out.write("        }\r\n");
      out.write("        #hd_qnb .visit .visit-num {\r\n");
      out.write("            display:inline-block;\r\n");
      out.write("            line-height:16px;\r\n");
      out.write("            padding:0 5px;\r\n");
      out.write("            margin-left:5px;\r\n");
      out.write("            border-radius:10px;\r\n");
      out.write("            background:#da22f5;\r\n");
      out.write("            color:#fff;\r\n");
      out.write("            font-size:10px\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hd_login {\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            right:0;\r\n");
      out.write("            top:60px\r\n");
      out.write("        }\r\n");
      out.write("        .hd_login li {\r\n");
      out.write("            float:left;\r\n");
      out.write("            margin:0 5px;\r\n");
      out.write("            border-left:1px solid #000000;\r\n");
      out.write("            padding-left:10px;\r\n");
      out.write("            line-height:13px\r\n");
      out.write("        }\r\n");
      out.write("        .hd_login li:first-child {border-left:0}\r\n");
      out.write("        .hd_login a {color:#000000}\r\n");
      out.write("\r\n");
      out.write("        .navbar{\r\n");
      out.write("            margin: 0px 20px 0px 20px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .nav_div{\r\n");
      out.write("            z-index: 101;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-top: thin solid #e5e5e5;\r\n");
      out.write("            border-bottom: 3px solid #ffd203;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("           \r\n");
      out.write("        }\r\n");
      out.write("        .nav_div.fixed{\r\n");
      out.write("        \tposition: fixed;\r\n");
      out.write("        \ttop: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \t$(window).on('scroll', function(){\r\n");
      out.write("    \t\tif($(document).scrollTop() > 200){\r\n");
      out.write("    \t\t\t$('.nav_div').addClass('fixed');\r\n");
      out.write("    \t\t}else{\r\n");
      out.write("    \t\t\t$('.nav_div').removeClass('flxed');\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\tif($(document).scrollTop() < 50){\r\n");
      out.write("    \t\t\t$('.nav_div').attr(\"class\",\"nav_div\");\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t})\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"hd\">\r\n");
      out.write("        <h1 id=\"hd_h1\"></h1>\r\n");
      out.write("        <div id=\"tnb\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <ul id=\"hd_qnb\">\r\n");
      out.write("                    <li><a href=\"\">상단메뉴 1</a></li>\r\n");
      out.write("                    <li><a href=\"\">상단메뉴 2</a></li>\r\n");
      out.write("                    <li><a href=\"\">상단메뉴 3</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"hd_wrapper\">\r\n");
      out.write("    \r\n");
      out.write("            <div id=\"logo\">\r\n");
      out.write("                <a href=\"\"><img src=\"../../images/logo.jpg\" alt=\"로고\" width=\"140px\" height=\"70px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"hd_sch_wr\">\r\n");
      out.write("                <fieldset id=\"hd_sch\">\r\n");
      out.write("                    <form name=\"fsearchbox\" method=\"get\" action=\"\" >\r\n");
      out.write("\t                    <input type=\"text\" name=\"stx\" id=\"sch_stx\" maxlength=\"20\" placeholder=\"검색어를 입력해주세요\">\r\n");
      out.write("\t                    <button type=\"submit\" id=\"sch_submit\" value=\"검색\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i><span class=\"sound_only\">검색</span></button>\r\n");
      out.write("                    </form>\r\n");
      out.write("    \r\n");
      out.write("                </fieldset>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"hd_login\">        \r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"\">사이드 메뉴 1</a></li>\r\n");
      out.write("                <li><a href=\"\">사이드 메뉴 2</a></li>\r\n");
      out.write("                <li><a href=\"\">사이드 메뉴 3</a></li>\r\n");
      out.write("    \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav_div\">\r\n");
      out.write("            <ul class=\"nav justify-content-center\">\r\n");
      out.write("                <li class=\"nav-item navbar\">\r\n");
      out.write("                  <a class=\"nav-link\" href=\"#\">대타 찾기</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item navbar\">\r\n");
      out.write("                  <a class=\"nav-link\" href=\"#\">업체 찾기</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item navbar\">\r\n");
      out.write("                  <a class=\"nav-link\" href=\"../../controller.do?command=home\">계약확인</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item navbar\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"../../controller.do?command=findnearcomform\">근처업체찾기</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                <li class=\"nav-item navbar\">\r\n");
      out.write("                  <a class=\"nav-link\" href=\"#\">마이페이지</a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div> \r\n");
      out.write("    </div>\r\n");
      out.write("<!-- } 상단 끝 -->\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div id=\"mainTop\">\r\n");
      out.write("\t    <div class=\"mainTop1\" >\t\r\n");
      out.write("            <div class=\"choice_box\" style=\"margin-left : 250px;\">\r\n");
      out.write("\t\t\t\t<h2 class=\"choice_title\">지역별 알바</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"choice_box\" style=\"border-left: none;\">\r\n");
      out.write("\t\t\t\t<h2 class=\"choice_title\">기간별 알바</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"mainTop2\">\r\n");
      out.write("\t        <div id=\"Login\" class=\"login-main\">\r\n");
      out.write("\t            <p class=\"login-main__guide\">로그인 후 다양한 서비스를 이용해보세요!</p>\r\n");
      out.write("\t            <div class=\"login-main__action\"><a href=\"\">로그인</a></div>\r\n");
      out.write("\t            <ul class=\"login-main__member\">\r\n");
      out.write("\t                <li><a href=\"\">회원가입</a></li>\r\n");
      out.write("\t                <li><a class=\"idSearch\" href=\"\">아이디 찾기</a></li>\r\n");
      out.write("\t                <li><a class=\"pwSearch\" href=\"\">비밀번호 찾기</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\t\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"mainTop3\">\r\n");
      out.write("\t        <div class=\"mini_title\">\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"mini_content\">\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("    \t<div class=\"mainTop2\">\r\n");
      out.write("\t        <div class=\"ad_banner\">\r\n");
      out.write("\t\t\t\t광고\r\n");
      out.write("\t        </div>\t\r\n");
      out.write("\t    </div>\r\n");
      out.write("   \t    <div class=\"mainTop3\" style=\"margin-top : 13px;\">\r\n");
      out.write("\t        <div class=\"mini_title\">\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"mini_content\">\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        \t<p>1. test</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- } 콘텐츠 끝 -->\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!-- 하단 시작 { -->\r\n");
      out.write("\r\n");
      out.write("<!-- } 하단 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
